BASE_CONFIGS = {
    "rk4_ieee9_restcn_noangle": {
        "data": {
            "t_step": 0.01,
            "outputs": [
                "$p_{m1}$",
                "$v_{1}$",
                "$\\omega_{2}$",
                "$v_{2}$",
                "$\\omega_{3}$",
                "$v_{3}$",
            ],
            "controls": ["$p_{d1}$", "$p_{d2}$", "$p_{d3}$"],
            "outputs_as_latent_states": [
                "$p_{m1}$",
                "$v_{1}$",
                "$\\omega_{2}$",
                "$v_{2}$",
                "$\\omega_{3}$",
                "$v_{3}$",
            ],
            "seq_len": 64,
            "hist_seq_len": 64,
            "overlap": 48,
        },
        "model": {
            "dynamics": {
                "type": "fxu",
                "stepper": "rk4",
                "latent_state_dim": 3 * 3 - 1,
                "act_fct": "silu",
                "n_layers": 1,
                "n_hidden": 128,
                "dropout": 0.0,
            },
            "encoder": {
                "type": "restcn",
                "n_layers": 1,
                "n_hidden": 32,
                "dropout": 0.1,
                "input_mode": "sequence",
                "input_sources": "yu",
            },
            "decoder": None,
        },
        "train": {
            "learning_rate": 5.22e-3,
            "n_epochs": 1000,
            "patience": 250,
            "warmup": 250,
            "grad_clip": 0.1,
            "batch_size": 2**8,
            "shuffle": True,
            "drop_last": False,
        },
        "meta": {
            "config_id": "noid",
        },
    },
    "rk4_ieee30_restcn_noangle": {
        "data": {
            "t_step": 0.01,
            "outputs": [
                "$p_{m1}$",
                "$v_1$",
                "$\\omega_{2}$",
                "$v_2$",
                "$p_{m3}$",
                "$v_3$",
                "$p_{m4}$",
                "$v_4$",
                "$p_{m5}$",
                "$v_5$",
                "$\\omega_{6}$",
                "$v_6$",
            ],
            "controls": [
                "$p_{d1}$",
                "$p_{d2}$",
                "$p_{d3}$",
                "$p_{d4}$",
                "$p_{d5}$",
                "$p_{d6}$",
            ],
            "outputs_as_latent_states": [
                "$p_{m1}$",
                "$v_1$",
                "$\\omega_{2}$",
                "$v_2$",
                "$p_{m3}$",
                "$v_3$",
                "$p_{m4}$",
                "$v_4$",
                "$p_{m5}$",
                "$v_5$",
                "$\\omega_{6}$",
                "$v_6$",
            ],
            "seq_len": 64,
            "hist_seq_len": 64,
            "overlap": 48,
        },
        "model": {
            "dynamics": {
                "type": "fxu",
                "stepper": "rk4",
                "latent_state_dim": 6 * 3 - 1,
                "act_fct": "silu",
                "n_layers": 1,
                "n_hidden": 1024,
                "dropout": 0.0,
            },
            "encoder": {
                "type": "restcn",
                "n_layers": 1,
                "n_hidden": 64,
                "dropout": 0.1,
                "input_mode": "sequence",
                "input_sources": "yu",
            },
            "decoder": None,
        },
        "train": {
            "learning_rate": 4.43e-3,
            "n_epochs": 1000,
            "patience": 250,
            "warmup": 250,
            "grad_clip": 0.1,
            "batch_size": 2**8,
            "shuffle": True,
            "drop_last": False,
        },
        "meta": {
            "config_id": "noid",
        },
    },
    "rk4_ieee39_restcn_noangle": {
        "data": {
            "t_step": 0.01,
            "outputs": [
                "$\\omega_{1}$",
                "$v_1$",
                "$\\omega_{2}$",
                "$v_2$",
                "$\\omega_{3}$",
                "$v_3$",
                "$\\omega_{4}$",
                "$v_4$",
                "$\\omega_{5}$",
                "$v_5$",
                "$\\omega_{6}$",
                "$v_6$",
                "$\\omega_{7}$",
                "$v_7$",
                "$\\omega_{8}$",
                "$v_8$",
                "$\\omega_{9}$",
                "$v_9$",
                "$\\omega_{10}$",
                "$v_{10}$",
            ],
            "controls": [
                "$p_{d1}$",
                "$p_{d2}$",
                "$p_{d3}$",
                "$p_{d4}$",
                "$p_{d5}$",
                "$p_{d6}$",
                "$p_{d7}$",
                "$p_{d8}$",
                "$p_{d9}$",
                "$p_{d10}$",
            ],
            "outputs_as_latent_states": [
                "$\\omega_{1}$",
                "$v_1$",
                "$\\omega_{2}$",
                "$v_2$",
                "$\\omega_{3}$",
                "$v_3$",
                "$\\omega_{4}$",
                "$v_4$",
                "$\\omega_{5}$",
                "$v_5$",
                "$\\omega_{6}$",
                "$v_6$",
                "$\\omega_{7}$",
                "$v_7$",
                "$\\omega_{8}$",
                "$v_8$",
                "$\\omega_{9}$",
                "$v_9$",
                "$\\omega_{10}$",
                "$v_{10}$",
            ],
            "seq_len": 64,
            "hist_seq_len": 64,
            "overlap": 48,
        },
        "model": {
            "dynamics": {
                "type": "fxu",
                "stepper": "rk4",
                "latent_state_dim": 10 * 3 - 1,
                "act_fct": "silu",
                "n_layers": 1,
                "n_hidden": 512,
                "dropout": 0.0,
            },
            "encoder": {
                "type": "restcn",
                "n_layers": 1,
                "n_hidden": 64,
                "dropout": 0.1,
                "input_mode": "sequence",
                "input_sources": "yu",
            },
            "decoder": None,
        },
        "train": {
            "learning_rate": 1.01e-3,
            "n_epochs": 1000,
            "patience": 250,
            "warmup": 250,
            "grad_clip": 0.1,
            "batch_size": 2**8,
            "shuffle": True,
            "drop_last": False,
        },
        "meta": {
            "config_id": "noid",
        },
    },
}
