BASE_CONFIGS = {
    'ieee9_graph_partiallatent': {
        'data': {
            't_step': 0.01,
            'outputs': ['$\\omega_{1}$', '$v_{1}$', '$\\omega_{2}$', '$v_{2}$', '$\\omega_{3}$', '$v_{3}$', '$\\omega_{4}$', '$v_{4}$', '$\\omega_{5}$', '$v_{5}$', '$\\omega_{6}$', '$v_{6}$', '$\\omega_{7}$', '$v_{7}$', '$\\omega_{8}$', '$v_{8}$', '$\\omega_{9}$', '$v_{9}$'],
            'controls': ['$p_{d1}$', '$p_{d2}$', '$p_{d3}$', '$p_{d4}$', '$p_{d5}$', '$p_{d6}$', '$p_{d7}$', '$p_{d8}$', '$p_{d9}$'],
            'outputs_as_latent_states': ['$\\omega_{1}$', '$v_{1}$'],
            'seq_len': 64,
            'hist_seq_len': 64,
            'overlap': 48,
        },
        'model': {
            'dynamics': {
                'type': 'graph',
                'stepper': 'rk4',
                'latent_state_dim': 3,
                'n_context': 8,
                'act_fct': 'silu',
                'n_layers': 2,
                'n_hidden': 256,
                'dropout': 0.0,
            },
            'encoder': {
                'type': 'restcn',
                'n_layers': -1,
                'n_hidden': 256,
                'dropout': 0.05,
                'input_mode': 'sequence',
                'input_sources': 'yu',
            },
            'decoder': {
                'n_layers': 2,
                'n_hidden': 256,
                'dropout': 0.0,
                'n_context': 0,
                'n_node_embedding': 0,
                'input_sources': 'x',
            },
            'graph': {
                'n_nodes': 9,
                'n_msg': 2,
                'n_hidden_msg': 256,
                'n_layers_msg': 2,
                'dropout_msg': 0.0,
                'n_node_embedding': 0,
                'n_edge_embedding': 0,
                'additive_messages': False,
                'degree_normalization': False,
                'edge_embeddings': True,
                'share_edge_embeddings': False,
                'n_edge_embed': 4,
                'adjacency_list': [
                    [0, 3],
                    [3, 0],
                    [3, 4],
                    [4, 3],
                    [4, 5],
                    [5, 4],
                    [2, 5],
                    [5, 2],
                    [5, 6],
                    [6, 5],
                    [6, 7],
                    [7, 6],
                    [1, 7],
                    [7, 1],
                    [7, 8],
                    [8, 7],
                    [3, 8],
                    [8, 3],
                ],
                'persistent_context': True,
            },
        },
        'train': {
            'learning_rate': 0.001,
            'n_epochs': 2500,
            'patience': 500,
            'warmup': 50,
            'grad_clip': float('inf'),
            'batch_size': 2 ** 9,
            'shuffle': True,
            'drop_last': True,
        },
        'meta': {
            'config_id': 'noid',
        },
    },
    'ieee9_monolith_partiallatent': {
        'data': {
            't_step': 0.01,
            'outputs': ['$\\omega_{1}$', '$v_{1}$', '$\\omega_{2}$', '$v_{2}$', '$\\omega_{3}$', '$v_{3}$', '$\\omega_{4}$', '$v_{4}$', '$\\omega_{5}$', '$v_{5}$', '$\\omega_{6}$', '$v_{6}$', '$\\omega_{7}$', '$v_{7}$', '$\\omega_{8}$', '$v_{8}$', '$\\omega_{9}$', '$v_{9}$'],
            'controls': ['$p_{d1}$', '$p_{d2}$', '$p_{d3}$', '$p_{d4}$', '$p_{d5}$', '$p_{d6}$', '$p_{d7}$', '$p_{d8}$', '$p_{d9}$'],
            'outputs_as_latent_states': ['$\\omega_{1}$', '$v_{1}$', '$\\omega_{2}$', '$v_{2}$', '$\\omega_{3}$', '$v_{3}$', '$\\omega_{4}$', '$v_{4}$', '$\\omega_{5}$', '$v_{5}$', '$\\omega_{6}$', '$v_{6}$', '$\\omega_{7}$', '$v_{7}$', '$\\omega_{8}$', '$v_{8}$', '$\\omega_{9}$', '$v_{9}$'],
            'seq_len': 64,
            'hist_seq_len': 64,
            'overlap': 48,
        },
        'model': {
            'dynamics': {
                'type': 'fxu',
                'stepper': 'rk4',
                'latent_state_dim': 9 * 3,
                'n_context': -1,
                'act_fct': 'silu',
                'n_layers': 2,
                'n_hidden': 256,
                'dropout': 0.0,
            },
            'encoder': {
                'type': 'restcn',
                'n_layers': -1,
                'n_hidden': 256,
                'dropout': 0.05,
                'input_mode': 'sequence',
                'input_sources': 'yu',
            },
            'decoder': None,
        },
        'train': {
            'learning_rate': 0.001,
            'n_epochs': 2500,
            'patience': 500,
            'warmup': 50,
            'grad_clip': float('inf'),
            'batch_size': 2 ** 9,
            'shuffle': True,
            'drop_last': True,
        },
        'meta': {
            'config_id': 'noid',
        },
    },
}
